image: alpine/edge
secrets:
 - 1b3fe3d9-ee86-4c7e-bd35-d0c87b6e12a9
sources:
  - git@git.sr.ht:~aaronkelly/gitscraper
environment:
  REPO_NAME: gitscraper
tasks:
- configure-git: |-
    git config --global user.email "aaronkelly@fastmil.com"
    git config --global user.name "Aaron Kelly"
- push-to-github: |-
    echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    cd "$REPO_NAME"
    git checkout master
    git remote set-url origin git@github.com:aaronpkelly/"$REPO_NAME"
    git config pull.rebase true
    git pull
    git add -u && git commit -m 'merge'
    git push -u origin master 